services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/data:/var/lib/mysql
    ports:
      - '3306:3306'
    restart: always
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    command: >
      bash -c "
        rm -f tmp/pids/server.pid && 
        rdbg -n --open --host 0.0.0.0 --port 12345 -c -- bundle exec rails s -e development -p 3000 -b '0.0.0.0'
      "
    volumes:
      - ./api:/api
    ports:
      - '3000:3000'
      - "12345:12345"
    depends_on:
      - db
    stdin_open: true
    tty: true
  front:
    build:
      context: .
      dockerfile: ./front/Dockerfile
    volumes:
      - ./front:/app/front
    ports:
      - 5173:5173
    command:
      sh -c 'npm run dev -- --host 0.0.0.0'
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true